---
- name: Create docker service systemd directory if it doesn't exist
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: get systemd version
  # noqa 303 - systemctl is called intentionally here
  shell: set -o pipefail && systemctl --version | head -n 1 | cut -d " " -f 2
  args:
    executable: /bin/bash
  register: systemd_version
  changed_when: false
  check_mode: false

- name: Write docker.service systemd file
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service
  register: docker_service_file
  notify: restart docker

- name: Write docker options systemd drop-in
  template:
    src: docker-options.conf.j2
    dest: "/etc/systemd/system/docker.service.d/docker-options.conf"
  notify: restart docker

- name: Copy docker orphan clean up script to the node
  copy:
    src: cleanup-docker-orphans.sh
    dest: "{{ bin_dir }}/cleanup-docker-orphans.sh"
    mode: 0755
  when: docker_orphan_clean_up | bool

- name: Write docker orphan clean up systemd drop-in
  template:
    src: docker-orphan-cleanup.conf.j2
    dest: "/etc/systemd/system/docker.service.d/docker-orphan-cleanup.conf"
  notify: restart docker
  when: docker_orphan_clean_up | bool

- meta: flush_handlers
