---
docker_version: '19.03'
docker_cli_version: "{{ 'latest' if docker_version != 'latest' and docker_version is version('18.09', '<') else docker_version }}"
docker_selinux_version: '17.03'

docker_package_info:
  pkgs:

docker_repo_key_info:
  repo_keys:

docker_repo_info:
  repos:

dockerproject_repo_key_info:
  repo_keys:

dockerproject_repo_info:
  repos:

docker_cgroup_driver: systemd

docker_dns_servers_strict: true

docker_container_storage_setup: false

# Ubuntu docker-ce repo
docker_ubuntu_repo_base_url: "https://download.docker.com/linux/ubuntu"
docker_ubuntu_repo_gpgkey: 'https://download.docker.com/linux/ubuntu/gpg'
docker_bin_dir: "/usr/bin"

# flag to enable/disable docker cleanup
docker_orphan_clean_up: false

# old docker package names to be removed
docker_remove_packages_apt:
  - docker
  - docker-engine
  - docker.io
